services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: vimo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chivacola123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vimo_network

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: spring_app
    depends_on:
      - db
    ports:
      - "8096:8096"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vimo_db
      DB_USER: postgres
      DB_PASSWORD: chivacola123
      SPRING_MAIL_USERNAME: fabricio.ladera@utec.edu.pe
      SPRING_MAIL_PASSWORD: lsqf vdki igzh cmln
    networks:
      - vimo_network

volumes:
  pgdata:

networks:
  vimo_network:
    driver: bridge